### PR TITLE
Faster random_mod

### PR DESCRIPTION
**Pull request by Sc00bz**
When the modulo is 2^(8*n) (or just above) the probability of success for each attempt is 1/256. This makes the worst case 50%.

### CODE REVIEW

**Comment by Sc00bz** [comment]
I don't know why I thought this project preferred `a = a & b` over the short hand. Also I just realized that doing `Limb::random_mod` on highest limb is better than the standard way. So the only real fix is for `Limb::random_mod` and `n_limbs = (n_bits + Limb::BIT_SIZE - 1) / Limb::BIT_SIZE`. Oh `n_limbs.saturating_sub(1)` can be `n_limbs - 1` since `n_limbs > 0` because `modulus` is `NonZero`.

Should I do a new pull request but minus all the stupid commits or fix it here?

**Comment by tarcieri** [comment]
@Sc00bz fixing it here is fine

**Comment by fjarri** [comment]
So, what's the status of this PR? I'd like to see this merged, can I help somehow?

**Comment by tarcieri** [comment]
@fjarri looks like it needs a rebase at least

**Comment by tarcieri** [comment]
Merged in #146

**Pull request closed without merging**
