### PR TITLE
Fix workflow YAML syntax

### PR DESCRIPTION
**Pull request by AaronFeickert**
My IDE reports that certain branch and path specifications in the GitHub actions configurations are not strictly valid YAML. This PR fixes accordingly.

### CODE REVIEW

**Comment by tarcieri** [comment]
FWIW we use standard templates for our CI YAML everywhere. This would be a notable divergence.

I guess it's more technically correct? Obviously GitHub Actions promotes a single string to an array of strings or it wouldn't work, though I suppose technically that violates lints which are written to the precise letter of GitHub's schema (which is still somewhat ill-specified given the actual semantics, but I digress)

**Comment by AaronFeickert** [comment]
Feel free to close if the resulting inconsistency with other repositories isn't worth it.

**Comment by tarcieri** [comment]
Maybe we can open some common issue to track updates to the boilerplate we should make everywhere

**Comment by AaronFeickert** [comment]
Not sure where that would be opened. Really this is just because my (apparently very picky) IDE was giving errors on this. Regardless, I'd still advocate to merge it to make the YAML gods happy unless there are likely to be headaches bringing in changes from other repositories.

**Review by tarcieri — APPROVED** [review]

**Comment by tarcieri** [comment]
Fine

**Pull request merged**
